### ISSUE TITLE
Can't install via Composer

### ISSUE THREAD

**Issue by karlmonson** [mvestil/omnipay-inoviopay#1]
It appears this package was either removed or never pushed to composer. When I try to install it gives the following error:

The requested package mvestil/omnipay-inoviopay could not be found in any version, there may be a typo in the package name.

**Comment by mvestil** [comment]
@karlmonson Yes not yet, i will add it once im done with the unit tests.

For now, please add in your composer.json under repositories

{
          "url": "https://github.com/mvestil/omnipay-inoviopay",
          "type": "git"
        }

**Comment by mvestil** [comment]
@karlmonson Was planning to create unit test first before uploading but did not have the time to do it.
Anyway, I just uploaded this package to packagist and I saw that you already uploaded a copy of my codes to packagist. 

Please use this package officially as I will be maintaining this and will push updates from time to time as we are working with InovioPay team. I will be pushing an update related to Void & Refund first week of April

If you can remove your upload in the packagist, would be better so we only have 1 package to maintain.

Thanks for this issue you filed, it serves as a reminder to me

**Comment by karlmonson** [comment]
Will do, thank you!
